version: 2.1

parameters:
  namespace:
    type: string
    default: usct
  playground:
    type: boolean
    default: false
  image:
    type: string
    default: "app/usct/frontend"

orbs:
  aws-cli: circleci/aws-cli@4.1.2
  helm: circleci/helm@3.0.0

commands:
  build_and_deploy:
    parameters:
      deploy:
        type: boolean
        default: false
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - helm/install_helm_client:
          version: v3.13.0
      - run:
          name: Setup env
          command: |
              echo "export IMAGE=${CONTAINER_REGISTRY}/<< pipeline.parameters.image >>" >> "$BASH_ENV"
      - run:
          name: Build docker image
          command: |
            docker build -t $IMAGE:latest .
      - run:
          name: Check Helm Chart
          command: |
            helm lint ./helm
      - when:
          condition: << parameters.deploy >>
          steps:
            - aws-cli/setup:
                role_arn: "${AWS_CIRCLECI_ROLE_ARN}"
                region: ${AWS_REGION}
                role_session_name: CircleCISession
                session_duration: '1800'
            - run:
                name: Push image
                command: |
                  aws ecr get-login-password | docker login --username AWS --password-stdin "${CONTAINER_REGISTRY}"
                  docker push "$IMAGE:latest"
            - run:
                name: Update kubeconfig
                command: |
                  aws eks update-kubeconfig --name ${EKS_CLUSTER}
            - run:
                name: Deploy project
                command: |
                  DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE:latest)
                  DIGEST="${DIGEST#*@}"
                  helm upgrade --install --wait --dependency-update --create-namespace \
                    --namespace << pipeline.parameters.namespace >> \
                    --set-string "container.image=${IMAGE}@${DIGEST}" \
                    usct-frontend ./helm

jobs:
  build:
    docker:
      - image: cimg/aws:2023.09
    steps:
      - build_and_deploy:
          deploy: false

  build-and-deploy:
    docker:
      - image: cimg/aws:2023.09
    steps:
      - build_and_deploy:
          deploy: true

workflows:
  # build every commit
  "Just build":
    when:
      and:
        - equal: [ false, << pipeline.parameters.playground >> ]
        - not:
            equal: [ 'main', << pipeline.git.branch >> ]
    jobs:
      - build:
          context: playground

  # build and deploy to playground depending on parameter
  "Build and deploy to playground":
    when:
      and:
        - equal: [ true, << pipeline.parameters.playground >> ]
        - equal: [ 'main', << pipeline.git.branch >> ]
    jobs:
      - build-and-deploy:
          context: playground
