export enum BUILDING_BLOCK {
  CONSENT = "CONSENT",
  IDENTITY = "IDENTITY",
  INFORMATION_MEDIATOR = "INFORMATION_MEDIATOR",
  DIGITAL_REGISTRIES = "DIGITAL_REGISTRIES",
  MESSAGING = "MESSAGING",
  PAYMENT = "PAYMENT",
  REGISTRATION = "REGISTRATION",
  SCHEDULING = "SCHEDULING",
  WORKFLOW = "WORKFLOW",
}
