export enum BUILDING_BLOCK {
  CONSENT = "CONSENT",
  AUTHENTICATION = "AUTHENTICATION",
  INFORMATION_MEDIATOR = "INFORMATION_MEDIATOR",
  DIGITAL_REGISTRIES = "DIGITAL_REGISTRIES",
  MESSAGING = "MESSAGING",
  PAYMENT = "PAYMENT",
  REGISTRATION = "REGISTRATION",
  SCHEDULING = "SCHEDULING",
  WORKFLOW = "WORKFLOW",
  SECURITY = "SECURITY",
}
